version: '3.9'

services:
  kontakjavadb:
    image: "mysql:8.0.32"
    container_name: kontakjavadb
    volumes:
      - kontakjavadb:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: kontakjavadb
    ports:
      - "33061:3306"
volumes:
  kontakjavadb:
    driver: local